config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :fan_comments
  resources :reviews
  resources :authors
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get'hello/index'
  get 'hello/view'
  get 'hello/list'
  get 'view/form_tag'
  post 'view/create'
  get 'view/keyword'
  post 'keyword/search'
end

app/models/author.rb
class Author < ApplicationRecord
  belongs_to :user
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:user_id, :name, :birth, :address, :ctype, :photo)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.slim
= form_for @author do |f|
  - if @author.errors.any?
    #error_explanation
      h2 = "#{pluralize(@author.errors.count, "error")} prohibited this author from being saved:"
      ul
        - @author.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :birth
    = f.date_select :birth
  .field
    = f.label :address
    = f.text_area :address
  .field
    = f.label :ctype
    = f.text_field :ctype
  .field
    = f.label :photo
    = f.text_field :photo
  .actions = f.submit

app/views/authors/edit.html.slim
h1 Editing author

== render 'form'

=> link_to 'Show', @author
'|
=< link_to 'Back', authors_path

app/views/authors/index.html.slim
h1 Listing authors

table
  thead
    tr
      th User
      th Name
      th Birth
      th Address
      th Ctype
      th Photo
      th
      th
      th

  tbody
    - @authors.each do |author|
      tr
        td = author.user
        td = author.name
        td = author.birth
        td = author.address
        td = author.ctype
        td = author.photo
        td = link_to 'Show', author
        td = link_to 'Edit', edit_author_path(author)
        td = link_to 'Destroy', author, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Author', new_author_path

app/views/authors/new.html.slim
h1 New author

== render 'form'

= link_to 'Back', authors_path

app/views/authors/show.html.slim
p#notice = notice

p
  strong User:
  = @author.user
p
  strong Name:
  = @author.name
p
  strong Birth:
  = @author.birth
p
  strong Address:
  = @author.address
p
  strong Ctype:
  = @author.ctype
p
  strong Photo:
  = @author.photo

=> link_to 'Edit', edit_author_path(@author)
'|
=< link_to 'Back', authors_path