config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :fan_comments
  resources :reviews
  resources :authors
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get'hello/index'
  get 'hello/view'
  get 'hello/list'
  get 'view/form_tag'
  post 'view/create'
  get 'view/keyword'
  post 'keyword/search'
end

app/models/fan_comment.rb
class FanComment < ApplicationRecord
end

app/controllers/fan_comments_controller.rb
class FanCommentsController < ApplicationController
  before_action :set_fan_comment, only: [:show, :edit, :update, :destroy]

  # GET /fan_comments
  # GET /fan_comments.json
  def index
    @fan_comments = FanComment.all
  end

  # GET /fan_comments/1
  # GET /fan_comments/1.json
  def show
  end

  # GET /fan_comments/new
  def new
    @fan_comment = FanComment.new
  end

  # GET /fan_comments/1/edit
  def edit
  end

  # POST /fan_comments
  # POST /fan_comments.json
  def create
    @fan_comment = FanComment.new(fan_comment_params)

    respond_to do |format|
      if @fan_comment.save
        format.html { redirect_to @fan_comment, notice: 'Fan comment was successfully created.' }
        format.json { render :show, status: :created, location: @fan_comment }
      else
        format.html { render :new }
        format.json { render json: @fan_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fan_comments/1
  # PATCH/PUT /fan_comments/1.json
  def update
    respond_to do |format|
      if @fan_comment.update(fan_comment_params)
        format.html { redirect_to @fan_comment, notice: 'Fan comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @fan_comment }
      else
        format.html { render :edit }
        format.json { render json: @fan_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fan_comments/1
  # DELETE /fan_comments/1.json
  def destroy
    @fan_comment.destroy
    respond_to do |format|
      format.html { redirect_to fan_comments_url, notice: 'Fan comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fan_comment
      @fan_comment = FanComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fan_comment_params
      params.require(:fan_comment).permit(:author_no, :name, :body, :deleted)
    end
end

app/helpers/fan_comments_helper.rb
module FanCommentsHelper
end

app/views/fan_comments/_form.html.slim
= form_for @fan_comment do |f|
  - if @fan_comment.errors.any?
    #error_explanation
      h2 = "#{pluralize(@fan_comment.errors.count, "error")} prohibited this fan_comment from being saved:"
      ul
        - @fan_comment.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :author_no
    = f.number_field :author_no
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :deleted
    = f.check_box :deleted
  .actions = f.submit

app/views/fan_comments/edit.html.slim
h1 Editing fan_comment

== render 'form'

=> link_to 'Show', @fan_comment
'|
=< link_to 'Back', fan_comments_path

app/views/fan_comments/index.html.slim
h1 Listing fan_comments

table
  thead
    tr
      th Author no
      th Name
      th Body
      th Deleted
      th
      th
      th

  tbody
    - @fan_comments.each do |fan_comment|
      tr
        td = fan_comment.author_no
        td = fan_comment.name
        td = fan_comment.body
        td = fan_comment.deleted
        td = link_to 'Show', fan_comment
        td = link_to 'Edit', edit_fan_comment_path(fan_comment)
        td = link_to 'Destroy', fan_comment, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Fan comment', new_fan_comment_path

app/views/fan_comments/new.html.slim
h1 New fan_comment

== render 'form'

= link_to 'Back', fan_comments_path

app/views/fan_comments/show.html.slim
p#notice = notice

p
  strong Author no:
  = @fan_comment.author_no
p
  strong Name:
  = @fan_comment.name
p
  strong Body:
  = @fan_comment.body
p
  strong Deleted:
  = @fan_comment.deleted

=> link_to 'Edit', edit_fan_comment_path(@fan_comment)
'|
=< link_to 'Back', fan_comments_path