config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :fan_comments
  resources :reviews
  resources :authors
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get'hello/index'
  get 'hello/view'
  get 'hello/list'
  get 'view/form_tag'
  post 'view/create'
  get 'view/keyword'
  post 'keyword/search'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:book_id, :user_id, :status, :body)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.slim
= form_for @review do |f|
  - if @review.errors.any?
    #error_explanation
      h2 = "#{pluralize(@review.errors.count, "error")} prohibited this review from being saved:"
      ul
        - @review.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :book
    = f.text_field :book
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :status
    = f.number_field :status
  .field
    = f.label :body
    = f.text_area :body
  .actions = f.submit

app/views/reviews/edit.html.slim
h1 Editing review

== render 'form'

=> link_to 'Show', @review
'|
=< link_to 'Back', reviews_path

app/views/reviews/index.html.slim
h1 Listing reviews

table
  thead
    tr
      th Book
      th User
      th Status
      th Body
      th
      th
      th

  tbody
    - @reviews.each do |review|
      tr
        td = review.book
        td = review.user
        td = review.status
        td = review.body
        td = link_to 'Show', review
        td = link_to 'Edit', edit_review_path(review)
        td = link_to 'Destroy', review, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Review', new_review_path

app/views/reviews/new.html.slim
h1 New review

== render 'form'

= link_to 'Back', reviews_path

app/views/reviews/show.html.slim
p#notice = notice

p
  strong Book:
  = @review.book
p
  strong User:
  = @review.user
p
  strong Status:
  = @review.status
p
  strong Body:
  = @review.body

=> link_to 'Edit', edit_review_path(@review)
'|
=< link_to 'Back', reviews_path